# Generated by Django 5.2.6 on 2025-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("credits_per_month", models.PositiveIntegerField(default=100)),
                (
                    "additional_credit_price",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=6),
                ),
                (
                    "paystack_plan_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("max_api_calls_per_hour", models.PositiveIntegerField(default=100)),
                ("max_bulk_emails", models.PositiveIntegerField(default=1000)),
                ("supports_api", models.BooleanField(default=False)),
                ("supports_bulk", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plans",
                "ordering": ["price"],
                "managed": True,
            },
        ),
    ]
