# Generated by Django 5.2.4 on 2025-07-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
        ("plan", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="plan.plan",
            ),
        ),
    ]
