# Generated by Django 5.2.6 on 2025-09-13 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paystack_customer_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "paystack_subscription_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("credits_remaining", models.PositiveIntegerField(default=100)),
                ("credits_used_this_month", models.PositiveIntegerField(default=0)),
                ("credits_reset_date", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "default_payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                ("last_credit_purchase", models.DateTimeField(blank=True, null=True)),
                ("total_credits_purchased", models.PositiveIntegerField(default=0)),
                (
                    "total_amount_spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("plan_start_date", models.DateTimeField(blank=True, null=True)),
                ("plan_end_date", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "current_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_profiles",
                        to="plan.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Credit Purchase"),
                            ("usage", "Email Validation"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus Credits"),
                            ("expired", "Credits Expired"),
                            ("plan_credits", "Plan Credits"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "paystack_payment_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "paystack_transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="billing.billingprofile",
                    ),
                ),
            ],
            options={
                "db_table": "credit_transactions",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmailValidationUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validation_request_id", models.CharField(max_length=128)),
                ("credits_consumed", models.PositiveIntegerField(default=1)),
                (
                    "cost_per_credit",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=6),
                ),
                ("validation_type", models.CharField(max_length=50)),
                ("email_count", models.PositiveIntegerField(default=1)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_usage",
                        to="billing.billingprofile",
                    ),
                ),
            ],
            options={
                "db_table": "email_validation_usage",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paystack_subscription_id",
                    models.CharField(max_length=128, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("past_due", "Past Due"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="billing.billingprofile",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
