# Generated by Django 5.2.6 on 2025-11-13 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("plan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "credits",
                    models.PositiveIntegerField(
                        help_text="Number of credits in package"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage off regular price",
                        max_digits=5,
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price before discount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Number of days until credits expire after purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "max_purchases_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum times a user can purchase this package",
                        null=True,
                    ),
                ),
                (
                    "total_available",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of packages available (for limited offers)",
                        null=True,
                    ),
                ),
                ("total_sold", models.PositiveIntegerField(default=0)),
                (
                    "paystack_plan_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "credit_packages",
                "ordering": ["sort_order", "-is_featured", "price"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CreditPackagePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("paystack_reference", models.CharField(max_length=128, unique=True)),
                (
                    "paystack_transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("credits_purchased", models.PositiveIntegerField()),
                ("credits_added_date", models.DateTimeField(blank=True, null=True)),
                ("credits_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "credit_package_purchases",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invoice number (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription Payment"),
                            ("credit_package", "Credit Package Purchase"),
                            ("credit_purchase", "Credit Purchase"),
                            ("refund", "Refund"),
                        ],
                        default="credit_package",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date invoice was created",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, help_text="Date invoice was paid", null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal before tax and discounts",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total discount applied",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total tax amount",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final total amount",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount paid",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="Currency code (NGN, USD, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "customer_address",
                    models.JSONField(
                        blank=True, default=dict, help_text="Billing address snapshot"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes or terms"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pdf_generated",
                    models.BooleanField(
                        default=False, help_text="Whether PDF has been generated"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file",
                        null=True,
                        upload_to="invoices/%Y/%m/",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-invoice_date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(help_text="Item description", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity of items",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per unit", max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total for this line (quantity * unit_price)",
                        max_digits=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique promo code (case-insensitive)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description of this promo code"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Discount"),
                            ("fixed", "Fixed Amount Discount"),
                            ("free_credits", "Free Credits Bonus"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount or credits",
                        max_digits=10,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total uses (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum uses per user"
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, help_text="Current total uses"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, help_text="When the code becomes valid", null=True
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="When the code expires", null=True
                    ),
                ),
                (
                    "minimum_purchase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum purchase amount required",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "first_purchase_only",
                    models.BooleanField(
                        default=False, help_text="Only valid for user's first purchase"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this code is currently active"
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        blank=True, help_text="Marketing campaign name", max_length=100
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
            ],
            options={
                "db_table": "promo_codes",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PromoCodeRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original price before discount",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount discounted", max_digits=10
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Final amount paid", max_digits=10
                    ),
                ),
                (
                    "bonus_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Bonus credits awarded"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "promo_code_redemptions",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="trial_converted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="trial_converted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billingprofile",
            name="trial_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="expired_at",
            field=models.DateTimeField(
                blank=True, help_text="Actual expiration timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="expiry_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when these credits will expire", null=True
            ),
        ),
        migrations.AddField(
            model_name="credittransaction",
            name="is_expired",
            field=models.BooleanField(
                default=False, help_text="Whether these credits have expired"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["billing_profile", "transaction_type"],
                name="credit_tran_billing_72af84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["expiry_date", "is_expired"],
                name="credit_tran_expiry__d5d1ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["-created_at"], name="credit_tran_created_34ce93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["paystack_payment_reference"],
                name="credit_tran_paystac_a63067_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackage",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="credit_pack_is_acti_9465dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackage",
            index=models.Index(
                fields=["sort_order", "price"], name="credit_pack_sort_or_a901b8_idx"
            ),
        ),
        migrations.AddField(
            model_name="creditpackagepurchase",
            name="billing_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_purchases",
                to="billing.billingprofile",
            ),
        ),
        migrations.AddField(
            model_name="creditpackagepurchase",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="billing.creditpackage",
            ),
        ),
        migrations.AddField(
            model_name="creditpackagepurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.billingprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="credit_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.creditpackage",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan.plan",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="valid_for_packages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Credit packages this code applies to (empty = all packages)",
                related_name="promo_codes",
                to="billing.creditpackage",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="valid_for_plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Plans this code applies to (empty = all plans)",
                related_name="promo_codes",
                to="plan.plan",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="billing_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_redemptions",
                to="billing.billingprofile",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="credit_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.creditpackage",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan.plan",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="promo_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redemptions",
                to="billing.promocode",
            ),
        ),
        migrations.AddField(
            model_name="promocoderedemption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promo_redemptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackagepurchase",
            index=models.Index(
                fields=["user", "status"], name="credit_pack_user_id_2fd6cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackagepurchase",
            index=models.Index(
                fields=["paystack_reference"], name="credit_pack_paystac_ab11a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackagepurchase",
            index=models.Index(
                fields=["-created_at"], name="credit_pack_created_27617b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="invoices_user_id_9940be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date"], name="invoices_invoice_e14adb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(fields=["code"], name="promo_codes_code_5b1d05_idx"),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["is_active", "valid_until"],
                name="promo_codes_is_acti_e865ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocoderedemption",
            index=models.Index(
                fields=["user", "promo_code"], name="promo_code__user_id_b182b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocoderedemption",
            index=models.Index(
                fields=["promo_code", "created_at"],
                name="promo_code__promo_c_3d6309_idx",
            ),
        ),
    ]
