# Generated by Django 5.2.6 on 2026-04-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_creditpackage_creditpackagepurchase_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Credit Purchase'), ('usage', 'Email Validation'), ('refund', 'Refund'), ('bonus', 'Bonus Credits'), ('expired', 'Credits Expired'), ('plan_credits', 'Plan Credits'), ('grant', 'Admin Grant'), ('deduction', 'Admin Deduction'), ('auto_reset', 'Automatic Monthly Reset'), ('manual_reset', 'Manual Billing Reset')], max_length=20),
        ),
    ]
