# Generated by Django 5.2.6 on 2026-07-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_reset_transaction_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='paystack', max_length=32)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_webhook_event',
                'managed': True,
                'indexes': [models.Index(fields=['provider', 'event_id'], name='processed_w_provide_8b7d56_idx'), models.Index(fields=['-created_at'], name='processed_w_created_239df0_idx')],
            },
        ),
    ]
