# Generated by Django 5.2.6 on 2025-09-13 09:18

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=128, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for this API key",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this key is used for",
                        null=True,
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="When this key was last used", null=True
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times this key has been used",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when key was created",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent when key was created",
                        null=True,
                    ),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last usage", null=True
                    ),
                ),
                (
                    "last_used_user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of last usage", null=True
                    ),
                ),
                (
                    "last_used_location",
                    models.TextField(
                        blank=True,
                        help_text="Geographic location of last usage",
                        null=True,
                    ),
                ),
                (
                    "last_used_device",
                    models.TextField(
                        blank=True,
                        help_text="Device information of last usage",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum requests per hour"
                    ),
                ),
                ("created_by_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_by_user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="api_keys_user_id_6e7352_idx"
                    ),
                    models.Index(fields=["key"], name="api_keys_key_291dcc_idx"),
                    models.Index(
                        fields=["last_used"], name="api_keys_last_us_f1be76_idx"
                    ),
                ],
            },
        ),
    ]
