# Generated by Django 5.2.4 on 2025-07-19 07:41

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apikey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default=secrets.token_urlsafe, max_length=128, unique=True
            ),
        ),
    ]
