"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config, Csv
import logging

logger = logging.getLogger(__name__)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Debug environment loading


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
OPENWEATHERMAP_API_KEY = os.environ.get("OPENWEATHERMAP_API_KEY", "")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

# ============================================================================
# OAuth Configuration
# ============================================================================
# OAuth providers: GitHub, GitLab, Google
#
# Required environment variables (add to .env file):
# - GITHUB_CLIENT_ID: Your GitHub OAuth App Client ID
# - GITHUB_CLIENT_SECRET: Your GitHub OAuth App Client Secret
# - GITLAB_CLIENT_ID: Your GitLab OAuth Application ID
# - GITLAB_CLIENT_SECRET: Your GitLab OAuth Application Secret
# - GOOGLE_CLIENT_ID: Your Google OAuth 2.0 Client ID
# - GOOGLE_CLIENT_SECRET: Your Google OAuth 2.0 Client Secret
#
# Optional OAuth settings:
# - OAUTH_REDIRECT_BASE_URI: Base URI for OAuth redirects (defaults to production URL)
# - OAUTH_ENABLED_PROVIDERS: Comma-separated list of enabled providers (defaults to all)
#
# Setup guides:
# - GitHub: https://github.com/settings/developers
# - GitLab: https://gitlab.com/-/profile/applications
# - Google: https://console.cloud.google.com/apis/credentials
# ============================================================================

# GitHub OAuth Configuration
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")

# GitLab OAuth Configuration
GITLAB_CLIENT_ID = os.getenv("GITLAB_CLIENT_ID")
GITLAB_CLIENT_SECRET = os.getenv("GITLAB_CLIENT_SECRET")

# Google OAuth Configuration
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

# OAuth Redirect URIs (used for callback URLs)
# These should match the redirect URIs configured in each OAuth provider's console
# Note: DEBUG is defined later, so we use a simple default for development
_DEBUG_MODE = os.getenv("DEBUG", "True").lower() == "true"
# For local development, use localhost (Google OAuth doesn't allow private IPs like 192.168.x.x)
# Set OAUTH_REDIRECT_BASE_URI in .env if you need a different value
# For Google OAuth: Use localhost or 127.0.0.1, NOT private IPs (192.168.x.x)
OAUTH_REDIRECT_BASE_URI = os.getenv(
    "OAUTH_REDIRECT_BASE_URI",
    "http://localhost:8000" if _DEBUG_MODE else "https://scrubimail.com",
)

# OAuth Callback Paths
OAUTH_CALLBACK_BASE_PATH = "/scrubimail/api/v1/auth/oauth"

# Construct full callback URLs
GITHUB_CALLBACK_URL = (
    f"{OAUTH_REDIRECT_BASE_URI}{OAUTH_CALLBACK_BASE_PATH}/github/callback/"
)
GITLAB_CALLBACK_URL = (
    f"{OAUTH_REDIRECT_BASE_URI}{OAUTH_CALLBACK_BASE_PATH}/gitlab/callback/"
)
GOOGLE_CALLBACK_URL = (
    f"{OAUTH_REDIRECT_BASE_URI}{OAUTH_CALLBACK_BASE_PATH}/google/callback/"
)

# OAuth Provider Availability Check
# Providers are considered available if both CLIENT_ID and CLIENT_SECRET are set
OAUTH_PROVIDERS_CONFIG = {
    "github": {
        "enabled": bool(GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET),
        "client_id": GITHUB_CLIENT_ID,
        "client_secret": GITHUB_CLIENT_SECRET,
        "callback_url": GITHUB_CALLBACK_URL,
    },
    "gitlab": {
        "enabled": bool(GITLAB_CLIENT_ID and GITLAB_CLIENT_SECRET),
        "client_id": GITLAB_CLIENT_ID,
        "client_secret": GITLAB_CLIENT_SECRET,
        "callback_url": GITLAB_CALLBACK_URL,
    },
    "google": {
        "enabled": bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET),
        "client_id": GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "callback_url": GOOGLE_CALLBACK_URL,
    },
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _DEBUG_MODE


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "channels",
    "apps.Authentication",
    # "apps.backend",
    "apps.User",
    "apps.Basemodel",
    "utils",
    "apps.validation",
    "apps.billing",
    "apps.apikey",
    "apps.plan",
    "apps.admin",
    "apps.changelog",
    "django_celery_results",
]

# Celery Configuration
# Falls back to REDIS_URL (the Redis service deployed in this Railway
# environment) so we never try to connect to a non-existent local Redis.
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_DEFAULT_QUEUE = "default"
# Route the SMTP mailbox-verification tasks to a dedicated queue consumed ONLY
# by the egress worker (the Hetzner box with port 25 open). Other workers must
# NOT consume `smtp_validation`, so they never attempt SMTP probes that would
# just time out / return "unknown".
CELERY_TASK_ROUTES = {
    "apps.validation.tasks.validate_email_task": {"queue": "smtp_validation"},
    "apps.validation.tasks.bulk_validate_emails_task": {"queue": "smtp_validation"},
    "apps.validation.tasks.verify_email_deep_task": {"queue": "smtp_validation"},
}
# Record a STARTED state when a worker picks a task up. The realtime endpoint
# uses it to tell "probe in progress, just slow" (STARTED) apart from "nobody
# is consuming the queue" (still PENDING) when its wait times out — only the
# latter trips the egress-unresponsive cooldown below.
CELERY_TASK_TRACK_STARTED = True

# Scheduled (beat) tasks. The disposable-domain blocklist is refreshed weekly so
# coverage keeps up with DEA services that rotate domains to evade static lists.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "refresh-disposable-domains-weekly": {
        "task": "apps.validation.tasks.refresh_disposable_domains_task",
        # Sundays at 03:00 UTC — off-peak. Keep it on the default queue (not the
        # egress smtp_validation queue): it only downloads and writes a file.
        "schedule": crontab(hour=3, minute=0, day_of_week=0),
        "options": {"queue": "default"},
    },
}

# Cache Configuration
# Shared cache for DNS/MX and domain-reputation lookups so validation hits are
# shared across all web/worker processes and survive restarts (vs. a per-process
# in-memory cache). Uses Django 5.x's built-in Redis backend (no extra dep).
# Falls back to local-memory if CACHE_REDIS_URL isn't set; the validator also
# degrades gracefully to an in-process cache if Redis is unreachable.
CACHE_REDIS_URL = os.getenv("CACHE_REDIS_URL") or REDIS_URL
if CACHE_REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": CACHE_REDIS_URL,
            "KEY_PREFIX": "scrubimail",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "scrubimail-locmem",
        }
    }

MIDDLEWARE = [
    # 'backend.middle_ware.ConditionalSlashMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"

import dj_database_url

if os.getenv("ON_HEROKU") == "1":
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            engine="django.db.backends.postgresql",
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "scrubimail",
            "USER": "postgres",
            "PASSWORD": "@Toshib123",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "User.User"

# Add custom authentication backends
AUTHENTICATION_BACKENDS = [
    "apps.Authentication.backends.EmailOrPhoneBackend",  # Custom backend for email/phone authentication
    "django.contrib.auth.backends.ModelBackend",  # Default backend as fallback
]

# Table name settings to remove app name prefix
TABLE_NAME_TEMPLATE = "{table_name}"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "backend.middle_ware.APIKeyAuthentication",
        "apps.Authentication.authentication.SuspensionAwareJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "backend.throttling.PlanBasedRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
        "plan_based": "100/hour",  # Fallback rate
        "bulk_validation": "100/hour",  # Fallback for bulk
        "plan_feature": "10000/hour",  # High rate for feature access checks (not time-based throttling)
    },
    "EXCEPTION_HANDLER": "backend.exception_handlers.custom_exception_handler",
    # Configure renderers so that responses are in camelCase.
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    # Configure parsers so that incoming camelCase keys are converted to snake_case.
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Always required: the frontend sends requests with credentials (withCredentials),
# so the browser requires Access-Control-Allow-Credentials: true on every response,
# including in production where DEBUG is False.
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:5173,http://192.168.100.12:5173",
    cast=Csv(),
)
CORS_ALLOWED_ORIGIN_REGEXES = config(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    default=r"^https://.*\.pages\.dev$,^https://.*\.scrubimail\.com$",
    cast=Csv(),
)

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")
if ALLOWED_HOSTS == ["*"]:
    ALLOWED_HOSTS = ["*"]


if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://192.168.100.12:5173",
        "http://localhost:5173",
    ]


# CORS Settings

# Allow all methods for development
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-refresh-token",
    "x-api-key",
]

# Expose custom headers to the frontend
CORS_EXPOSE_HEADERS = [
    "Authorization",
    "X-Refresh-Token",
]

# settings.py
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("redis://127.0.0.1:6379/0")],  # Redis URL format
#         },
#     },
# }

logger.info(f"CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")

logger.info(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Use REDIS_URL (the Redis service deployed in this Railway
            # environment) instead of a hardcoded host/IP.
            "hosts": [REDIS_URL],
        },
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
        },
        "airflow": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# --- mailing system setting ----
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"

# Print email configuration for debugging
print("=== Email Configuration ===")
print(f"DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
print(f"EMAIL_HOST: {EMAIL_HOST}")
print(f"EMAIL_PORT: {EMAIL_PORT}")
print(f"EMAIL_HOST_USER: {EMAIL_HOST_USER}")
print(
    f"EMAIL_HOST_PASSWORD: {'*' * len(EMAIL_HOST_PASSWORD) if EMAIL_HOST_PASSWORD else 'None'}"
)
print(f"EMAIL_USE_TLS: {EMAIL_USE_TLS}")
print("=========================")
print("=== CORS Configuration ===")
print(f"CORS_ALLOWED_ORIGINS: {CORS_ALLOWED_ORIGINS}")
print(f"CORS_ALLOWED_ORIGIN_REGEXES: {CORS_ALLOWED_ORIGIN_REGEXES}")
print("=========================")
print("=== ALLOWED_HOSTS ===")
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print("=========================")
print("=== DEBUG ===")
print(f"DEBUG: {DEBUG}")

APPEND_SLASH = False

# --- Paystack Configuration ---
# Paystack API Keys (get these from Paystack Dashboard)
PAYSTACK_PUBLIC_KEY = os.getenv(
    "PAYSTACK_PUBLIC_KEY",
)  # Test public key for development
PAYSTACK_SECRET_KEY = os.getenv(
    "PAYSTACK_SECRET_KEY",
)  # Test secret key for development

# Paystack Webhook Configuration
PAYSTACK_WEBHOOK_SECRET = os.getenv("PAYSTACK_WEBHOOK_SECRET")

print("Paystack WEBHOOK Key:", PAYSTACK_WEBHOOK_SECRET)
# Paystack Configuration
PAYSTACK_LIVE_MODE = False  # Set to True for production
PAYSTACK_CURRENCY = (
    "NGN"  # Legacy default; prefer PAYSTACK_CHARGE_CURRENCY for API calls
)
PAYSTACK_SUPPORTED_CURRENCIES = ["NGN", "USD", "GHS", "ZAR"]  # Supported currencies

# Currency Paystack actually settles/charges in for this business (must match dashboard).
# Use GHS while USD is not enabled; set to USD (and match Plan.currency) after Paystack approves USD.
PAYSTACK_CHARGE_CURRENCY = os.getenv("PAYSTACK_CHARGE_CURRENCY", "GHS")

# USD→GHS: primary source is CurrencyFreaks (see CURRENCYFREAKS_API_KEY); this is the fallback
# if the API fails or the key is unset. Changing live/fallback rates does not update existing
# Paystack plans (clear Plan.paystack_plan_code to recreate).
PAYSTACK_FX_USD_TO_GHS = os.getenv("PAYSTACK_FX_USD_TO_GHS", "15.0")
# CurrencyFreaks (https://currencyfreaks.com/) — free tier for latest rates
CURRENCYFREAKS_API_KEY = os.getenv("CURRENCYFREAKS_API_KEY", "")
CURRENCYFREAKS_REQUEST_TIMEOUT = int(os.getenv("CURRENCYFREAKS_REQUEST_TIMEOUT", "10"))
# Applied to the API rate only (not to fallback): e.g. 1.05 = 5% buffer for fees/FX drift
PAYSTACK_FX_BUFFER = os.getenv("PAYSTACK_FX_BUFFER", "1.05")
PAYSTACK_FX_CACHE_TTL = int(os.getenv("PAYSTACK_FX_CACHE_TTL", "3600"))

# Paystack minimum charge in GHS (major units); conversion must meet this.
PAYSTACK_MIN_GHS_MAJOR = os.getenv("PAYSTACK_MIN_GHS_MAJOR", "2.00")

# Frontend base (Vite default :5173). Used for email links and Paystack callback fallbacks.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").rstrip("/")

# --- OAuth / social login (Issue 11) ----------------------------------------
# Where the OAuth callback redirects the browser after login. NO environment-
# specific host or private IP is hardcoded in the auth code — it all comes from
# here. The user-supplied ?redirect_uri is validated against the allowlist to
# prevent an open redirect that would leak the one-time auth code.
OAUTH_FRONTEND_CALLBACK_URL = os.getenv(
    "OAUTH_FRONTEND_CALLBACK_URL", f"{FRONTEND_URL}/oauth/callback"
)
OAUTH_ALLOWED_REDIRECT_URIS = [
    u.strip()
    for u in os.getenv(
        "OAUTH_ALLOWED_REDIRECT_URIS", OAUTH_FRONTEND_CALLBACK_URL
    ).split(",")
    if u.strip()
]
# The browser redirect carries only this opaque single-use code (never tokens);
# the SPA exchanges it over POST within this many seconds.
OAUTH_EXCHANGE_CODE_TTL = int(os.getenv("OAUTH_EXCHANGE_CODE_TTL", 120))

# Paystack return URLs — default to same origin as FRONTEND_URL (override per env in production)
PAYMENT_SUCCESS_URL = os.getenv(
    "PAYMENT_SUCCESS_URL", f"{FRONTEND_URL}/billing/payment/success"
)
PAYMENT_CANCEL_URL = os.getenv(
    "PAYMENT_CANCEL_URL", f"{FRONTEND_URL}/billing/payment/cancelled"
)
PAYMENT_FAILED_URL = os.getenv(
    "PAYMENT_FAILED_URL", f"{FRONTEND_URL}/billing/payment/failed"
)

# Paystack Features Configuration
PAYSTACK_FEATURES = {
    "payment_intents": True,
    "payment_methods": True,
    "customers": True,
    "refunds": True,
    "webhooks": True,
    "subscriptions": True,  # Paystack supports subscriptions
}

# Logging configuration for Paystack
LOGGING["loggers"]["paystack"] = {
    "handlers": ["console"],
    "level": "INFO",
    "propagate": False,
}

LOGGING["loggers"]["apps.billing"] = {
    "handlers": ["console"],
    "level": "INFO",
    "propagate": False,
}

MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

# Email Configuration
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@scrubimail.com")

# ============================================================================
# Email Validation Configuration
# ============================================================================
# SMTP mailbox verification is what produces ZeroBounce-style "valid" answers.
# It REQUIRES a host with outbound port 25 open + a PTR record matching the
# HELO host + SPF on the MAIL FROM domain. Cloud hosts (AWS/GCP/Azure/Heroku)
# block port 25, so leave this OFF there and run it on a dedicated egress
# worker. The realtime web path never does SMTP (stays fast); the Celery
# (deep) path does. Without SMTP, unconfirmable mailboxes return status
# "unknown", never "valid".
VALIDATION_SMTP_ENABLED = os.getenv("VALIDATION_SMTP_ENABLED", "False") == "True"
VALIDATION_SMTP_TIMEOUT = int(os.getenv("VALIDATION_SMTP_TIMEOUT", 3))
VALIDATION_SMTP_STARTTLS = os.getenv("VALIDATION_SMTP_STARTTLS", "True") == "True"
# MUST be a real domain you control: HELO host needs a matching PTR record,
# MAIL FROM domain needs SPF, or major providers will tarpit/refuse the probe.
VALIDATION_SMTP_HELO_HOST = os.getenv("VALIDATION_SMTP_HELO_HOST", "scrubimail.com")
VALIDATION_SMTP_MAIL_FROM = os.getenv(
    "VALIDATION_SMTP_MAIL_FROM", "verify@scrubimail.com"
)
# Circuit breaker: after this many consecutive total SMTP failures, skip SMTP
# for BLOCK_TTL seconds (returns "unknown" instantly instead of timing out).
# On a reliable egress host you can raise the threshold or set TTL to 0.
VALIDATION_SMTP_FAILURE_THRESHOLD = int(
    os.getenv("VALIDATION_SMTP_FAILURE_THRESHOLD", 3)
)
VALIDATION_SMTP_BLOCK_TTL = int(os.getenv("VALIDATION_SMTP_BLOCK_TTL", 600))
# Catch-all detection is cached per domain so we probe a garbage address at
# most once per domain per TTL (default 24h), never once per deliverable
# address. Reusing the live SMTP session (RSET + RCPT) keeps it to one
# connection per address in the common case.
VALIDATION_CATCHALL_TTL = int(os.getenv("VALIDATION_CATCHALL_TTL", 86400))

# Per-kind cache TTLs (seconds) — replaces the old single 5-minute TTL so each
# kind of lookup lives as long as it is actually stable.
VALIDATION_CACHE_TTL_DNS = int(os.getenv("VALIDATION_CACHE_TTL_DNS", 21600))  # 6h
VALIDATION_CACHE_TTL_REPUTATION = int(
    os.getenv("VALIDATION_CACHE_TTL_REPUTATION", 86400)  # 24h
)
# NXDOMAIN / no-records answers change more often (domain just registered), so
# cache them briefly.
VALIDATION_CACHE_TTL_NEGATIVE_DNS = int(
    os.getenv("VALIDATION_CACHE_TTL_NEGATIVE_DNS", 3600)  # 1h
)

# Greylisting (SMTP 450): the server asked us to retry later. Re-probe once after
# this delay, up to this many times, before finalizing as unknown/greylisted.
VALIDATION_GREYLIST_RETRY_DELAY = int(
    os.getenv("VALIDATION_GREYLIST_RETRY_DELAY", 600)  # 10 min
)
VALIDATION_GREYLIST_MAX_RETRIES = int(os.getenv("VALIDATION_GREYLIST_MAX_RETRIES", 2))

# Try up to this many MX hosts, but ONLY advancing to the next when the previous
# failed to CONNECT — never re-probe a host that already answered.
VALIDATION_SMTP_MAX_MX_HOSTS = int(os.getenv("VALIDATION_SMTP_MAX_MX_HOSTS", 3))

# --- Realtime endpoint (deep verification within a hard time budget) ---------
# The customer-facing single-validation endpoint performs FULL verification by
# default within this wall-clock budget: the SMTP probe is enqueued to the
# smtp_validation queue (the egress worker) and the request waits for the
# verdict. If the budget expires, the rate limiter denies a slot, or the egress
# breaker is open, it returns an honest `unknown` with the appropriate
# sub_status — never blocks past the budget, never fakes `valid`. Pass
# ?mode=fast (or deep=false) for the sub-100ms syntax/DNS-only path.
VALIDATION_REALTIME_BUDGET_SECONDS = int(
    os.getenv("VALIDATION_REALTIME_BUDGET_SECONDS", 8)
)
# If a realtime wait times out while the probe is still unclaimed (no worker on
# the smtp_validation queue), skip the wait for this many seconds so requests
# degrade instantly instead of each burning the full budget. 0 disables.
VALIDATION_EGRESS_UNRESPONSIVE_COOLDOWN = int(
    os.getenv("VALIDATION_EGRESS_UNRESPONSIVE_COOLDOWN", 60)
)
# Shared result cache (keyed on sha256(email)) checked before any network work;
# deep Celery verifications write to it too, so bulk work warms the realtime path.
VALIDATION_RESULT_CACHE_TTL = int(
    os.getenv("VALIDATION_RESULT_CACHE_TTL", 604800)  # 7 days for terminal results
)
VALIDATION_RESULT_CACHE_TTL_UNKNOWN = int(
    os.getenv("VALIDATION_RESULT_CACHE_TTL_UNKNOWN", 86400)  # 1 day for unknown
)

# --- Per-provider SMTP rate limiting (protects the egress IP reputation) -----
# Conservative on purpose: loosen later with data, never the reverse. Limits are
# keyed on the MX provider fingerprint (google, microsoft, yahoo, proofpoint,
# mimecast, other) and enforced via the shared Redis cache across all workers.
VALIDATION_SMTP_RATE_LIMIT_ENABLED = (
    os.getenv("VALIDATION_SMTP_RATE_LIMIT_ENABLED", "True") == "True"
)
VALIDATION_SMTP_MAX_CONCURRENT_PER_PROVIDER = int(
    os.getenv("VALIDATION_SMTP_MAX_CONCURRENT_PER_PROVIDER", 2)
)
VALIDATION_SMTP_MAX_PROBES_PER_MINUTE_PER_PROVIDER = int(
    os.getenv("VALIDATION_SMTP_MAX_PROBES_PER_MINUTE_PER_PROVIDER", 10)
)
VALIDATION_SMTP_MAX_PROBES_PER_MINUTE_GLOBAL = int(
    os.getenv("VALIDATION_SMTP_MAX_PROBES_PER_MINUTE_GLOBAL", 20)
)
# On 421 (or this many repeated 4xx), pause probes to that provider this long.
VALIDATION_SMTP_PROVIDER_COOLDOWN = int(
    os.getenv("VALIDATION_SMTP_PROVIDER_COOLDOWN", 900)
)
VALIDATION_SMTP_SOFT_FAIL_THRESHOLD = int(
    os.getenv("VALIDATION_SMTP_SOFT_FAIL_THRESHOLD", 3)
)
# Safety TTL on the per-provider concurrency counter (frees a crashed worker's
# slot); and how long a rate-limited bulk address waits before the task retries.
VALIDATION_SMTP_CONCURRENCY_TTL = int(
    os.getenv("VALIDATION_SMTP_CONCURRENCY_TTL", 120)
)
# Merged disposable-domain feed (baseline + downloaded feeds), maintained by the
# update_disposable_domains management command / weekly beat task. Defaults to a
# writable file next to the bundled baseline (gitignored). Loaded on top of the
# bundled baseline; workers reload it via mtime when the weekly refresh runs.
VALIDATION_DISPOSABLE_DOMAINS_FILE = os.getenv(
    "VALIDATION_DISPOSABLE_DOMAINS_FILE",
    os.path.join(BASE_DIR, "apps", "validation", "data", "disposable_domains_external.txt"),
)
# Primary source for the weekly refresh (the maintained community dataset).
VALIDATION_DISPOSABLE_SOURCE_URL = os.getenv(
    "VALIDATION_DISPOSABLE_SOURCE_URL",
    "https://raw.githubusercontent.com/disposable-email-domains/"
    "disposable-email-domains/master/disposable_email_domains.txt",
)
# Optional extra feeds (comma-separated URLs), merged with the primary source.
VALIDATION_DISPOSABLE_EXTRA_FEEDS = [
    u.strip()
    for u in os.getenv("VALIDATION_DISPOSABLE_EXTRA_FEEDS", "").split(",")
    if u.strip()
]

# Bulk jobs run entirely in Celery (never inline in the HTTP request). Addresses
# are processed in chunks of this size; progress is persisted after each chunk.
VALIDATION_BULK_CHUNK_SIZE = int(os.getenv("VALIDATION_BULK_CHUNK_SIZE", 100))

# Optional data-driven spam-trap domain list (one domain per line). A domain
# here classifies as do_not_mail/spamtrap_detected. Empty by default — the
# keyword heuristic is only a weak risk-score signal and never classifies, so
# legitimate services (e.g. mailtrap.io) are not mislabelled as traps.
VALIDATION_SPAMTRAP_DOMAINS_FILE = os.getenv("VALIDATION_SPAMTRAP_DOMAINS_FILE", None)

# Prevent Heroku from running collectstatic on deploy
if os.environ.get("DISABLE_COLLECTSTATIC", "") == "1":
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
