# Generated by Django 5.2.6 on 2025-09-13 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainReputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("reputation_score", models.IntegerField(default=50)),
                ("is_disposable", models.BooleanField(default=False)),
                ("is_corporate", models.BooleanField(default=False)),
                ("tld_risk", models.BooleanField(default=False)),
                ("spam_trap_risk", models.FloatField(default=0.0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "domain_reputation",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["domain"], name="domain_repu_domain_f7d635_idx"
                    ),
                    models.Index(
                        fields=["reputation_score"],
                        name="domain_repu_reputat_245a5e_idx",
                    ),
                    models.Index(
                        fields=["is_disposable"], name="domain_repu_is_disp_5efe3b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BulkValidationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("emails", models.JSONField(default=list)),
                ("total_emails", models.IntegerField(default=0)),
                ("total_processed", models.IntegerField(default=0)),
                ("progress", models.IntegerField(default=0)),
                ("results_summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bulk_validation_job",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="bulk_valida_user_id_79cd24_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="bulk_valida_status_405d5e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("breakdown", models.JSONField(default=dict)),
                ("suggestions", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("bulk", "Bulk"),
                            ("api", "API"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_validation",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="email_valid_user_id_6f5b7a_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="email_valid_status_4df5a0_idx",
                    ),
                    models.Index(fields=["email"], name="email_valid_email_3107d6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidationStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_validations", models.IntegerField(default=0)),
                ("valid_emails", models.IntegerField(default=0)),
                ("invalid_emails", models.IntegerField(default=0)),
                ("risky_emails", models.IntegerField(default=0)),
                ("high_risk_emails", models.IntegerField(default=0)),
                ("avg_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "validation_stats",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="validation__user_id_904a1c_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
