# Generated by Django 5.2.6 on 2026-07-10 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='bulk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='validation.bulkvalidationjob'),
        ),
        migrations.AddIndex(
            model_name='emailvalidation',
            index=models.Index(fields=['bulk_job', 'status'], name='email_valid_bulk_jo_d31286_idx'),
        ),
    ]
